# Exercise 2.B Cleaning up Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Creating a DataFrame using csv file
df = pd.read_csv("test_data.csv")
df

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
2   3  Charlie  22.0    Chicago   -1.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [3]:
# Showing column statistics using method
df.describe()

            ID       Age      Score
count  8.00000   6.00000   7.000000
mean   4.50000  25.00000  66.285714
std    2.44949   6.78233  32.576650
min    1.00000  18.00000  -1.000000
25%    2.75000  19.75000  60.000000
50%    4.50000  23.50000  78.000000
75%    6.25000  29.50000  87.500000
max    8.00000  35.00000  92.000000

## Filtering a DataFrame

In [4]:
# Filtering and displaying rows where Age is greater than 18
filter_age = df[df['Age'] > 18]
print(filter_age)

# the inner part df['Age'] > 18 is a filter/mask that stores the TRUE/FALSE series where the condition is met
# the outer brackets take that series and return the actaul rows where the value is true

   ID     Name   Age     City  Score
0   1   Alicia  25.0       NY   85.0
2   3  Charlie  22.0  Chicago   -1.0
3   4  Dominic  19.0  Houston   65.0
4   5      Eve  31.0  Phoenix   78.0
5   6    Frank  35.0   Boston    NaN

In [5]:
# Filtering and Displaying rows where Score is greater than 50 and less than 100
# When you have 2 conditions, you need to use & and  wrap each condition in its own ()
# Pandas uses & for AND and | for OR
# Both have to be true regardless of which side they're on
filter_score = df[(df['Score'] > 50) & (df['Score'] < 100)]
print(filter_score)

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

## Modifying a DataFrame

In [6]:
# Creating a new variable that stores a copy of the DataFrame but cleaned. Original is untouched
# Using the drop function to remove rows where Score is invalid(less than 0)
# drop is for intentional data
# dropna is for all missing values
df_cleaned = df.drop(df[df['Score'] < 0].index)
# df.drop() combines boolean indexing and a condition to remove specific rows
# The inner mask df['Score'] < 0 creates a True/False Series identifying where the condition is met
# The outer wrap df[df['Score'] < 0] grabs the actual rows where the condition is True
# .index extracts the index labels of those rows
# .drop() then knows and removes the rows with those index labels from the DataFrame

df_cleaned

   ID     Name   Age       City  Score
0   1   Alicia  25.0         NY   85.0
1   2      Bob   NaN         LA   92.0
3   4  Dominic  19.0    Houston   65.0
4   5      Eve  31.0    Phoenix   78.0
5   6    Frank  35.0     Boston    NaN
6   7    Grace   NaN     Austin   55.0
7   8    Heidi  18.0  San Diego   90.0

In [7]:
# Dropping a city column
df_cleaned = df_cleaned.drop("City", axis = 1)
# axis=1 targets columns because the operation moves horizontally across the DataFrame to find them
# axis=0 targets rows because the operation moves vertically down the DataFrame to find them
# drop() takes the column/row name and axis direction as parameters
# Think of a grid, 0 is vertical axis and 1 is horizontal axis
# drop can remove columns with column name and the the axis postion as parameters
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob   NaN   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace   NaN   55.0
7   8    Heidi  18.0   90.0

In [8]:
# Reaplacing missing Age values with the mean of Age in DataFrame
df_cleaned['Age'] = df_cleaned['Age'].fillna(df_cleaned['Age'].mean())
df_cleaned
# .fillna replaces missing values
# I want the mean of the cleaned DataFrame because it has no invalid rows
# ['Age'] specifies and targets the Age column

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [9]:
# Replacing score values of 0 with the mean Score using replaced()
# .replace() replaces specific values
# It needs two arguments, what to replace and what to replace it with
df_cleaned['Score'] = df_cleaned['Score'].replace(0, df_cleaned['Score'].mean())
df_cleaned

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
5   6    Frank  35.0    NaN
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [10]:
# Removing any NaN values using .dropna()
df_cleaned = df_cleaned.dropna()
df_cleaned

# We need to remove it to avoid unreliable resujlts when doing analysis or calculations since there's no score

   ID     Name   Age  Score
0   1   Alicia  25.0   85.0
1   2      Bob  25.6   92.0
3   4  Dominic  19.0   65.0
4   5      Eve  31.0   78.0
6   7    Grace  25.6   55.0
7   8    Heidi  18.0   90.0

In [11]:
# Setting the ID column as the index labels
# set_index() moves the ID column out of the data and into the index, removing it automatically
df_cleaned = df_cleaned.set_index('ID')
df_cleaned

# Here we replace the default numeric index with the actual ID values
# Setting ID as the index makes lookups more easier. Instead of searching by row number,
# you can search by the actual record ID which maps directly to a real entity.
# It also makes merging DataFrames easier when joining on a shared ID.

       Name   Age  Score
ID
1    Alicia  25.0   85.0
2       Bob  25.6   92.0
4   Dominic  19.0   65.0
5       Eve  31.0   78.0
7     Grace  25.6   55.0
8     Heidi  18.0   90.0