# Exercise 2.C Working with Multiple DataFrames

In [2]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [3]:
# Creating the DataFrame from dataset
data = {
    'Product': ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North'],
    'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],
    'Price': [100, 200, 150, 100, 200, 150, 100, 200, 150]
}

df_sales = pd.DataFrame(data)
df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

In [4]:
# Adding new column called Revenue to DataFrame
df_sales["Revenue"] = df_sales['Units_Sold'] * df_sales['Price']

print("\n******** Updated Sales Table ********\n")
print(df_sales)

# Total Units_Sold and total Revenue across all products and regions
# Double brackets are used because the outer [] is the DataFrame indexing operator
# and the inner [] is a Python list of column names
# Single brackets select one column; double brackets select multiple columns as a list\

print("\n Total Units Sold | Total Revenue")
print(df_sales[['Units_Sold', 'Revenue']].sum())

# Average Units_Sold and average Revenue
print("\n Average Units Sold | Average Total Revenue")
print(df_sales[['Units_Sold', 'Revenue']].mean())

******** Updated Sales Table ********

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

 Total Units Sold | Total Revenue
Units_Sold      105
Revenue       16000
dtype: int64

 Average Units Sold | Average Total Revenue
Units_Sold      11.666667
Revenue       1777.777778
dtype: float64

## Grouping Data

In [5]:
# Using groupby to group df_sales by Product and calculate the total Units_Sold and total
# revenue for each product
# groupby splits DataFrame into groups based on a column, then applying an aggregation function
# df.groupby('column_name')['column_to_aggregate'].function()
# groupby() groups all rows that share the same value in a column together
# Unlike .sum() alone which gives one total for everything, groupby keeps groups separate
# Instead of 9 individual rows, we get 3 rows — one per product (A, B, C)
# .sum() then adds up the Units_Sold and Revenue for each product individually
df_sales.groupby('Product')[['Units_Sold', 'Revenue']].sum()

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

In [6]:
# Using groupby() to group df_sales by Region and calculate the average Units_Sold and
# and average Revenue for each region.
# Splitting Database by Region column, and for each region calculating the average Units_Sold per
# Region and average revenue per region
df_sales.groupby('Region')[['Units_Sold', 'Revenue']].mean()
#.round(2) can be used to round

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

In [7]:
# Using groupby to to group df_sales by both Product and Region and calculate the sum of 
# Units_Sold and revenue for each combo
# Splitting Database by Region and Product column, so I'll get the sum for each product sold 
# in each region and the revenue for each region based on that product
df_sales.groupby(['Product', 'Region'])[['Units_Sold', 'Revenue']].sum()\
# When grouping by multiple columns, they must be in a list

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

In [8]:
# Using sort_values() method to sort Units_Sold in ascending order
# df.sort_values("col")
print("----- Lowest to Highest Units Sold -----\n")
sorted_df_sales = df_sales.sort_values('Units_Sold', ascending=True)
print(sorted_df_sales)
# ascending is the default so you can technically leave it empty)

----- Lowest to Highest Units Sold -----

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [9]:
# Using sort_values() method to sort Revenue in descending order
print("----- Individual Sales Entries by Highest Revenue  -----\n")
sorted_df_revenue = df_sales.sort_values('Revenue', ascending=False)
print(sorted_df_revenue)
# descending can never be a paramter because the default is always ascending, so it must 
# either be True or False. Use = False for descending

----- Individual Sales Entries by Highest Revenue  -----

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
8       C  North          15    150     2250
5       C  South          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [10]:
# Using .rank() method to rank Revenue values in descending order in a new column
# Highested revenue = rank 1
# Syntax: df["col"].rank()
df_sales["Revenue_Rank"] = df_sales['Revenue'].rank(ascending=False)
df_sales

# Note: rows 1 and 2 both have Revenue 3000 (a tie), so pandas averages ranks 1 and 2
# giving both a rank of 1.5 instead of rank 1 — this is pandas' default tie-breaking behavior

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000           7.0
1       B  South          15    200     3000           1.5
2       C   East          20    150     3000           1.5
3       A   West           5    100      500           9.0
4       B  North          10    200     2000           5.0
5       C  South          15    150     2250           3.5
6       A   East          10    100     1000           7.0
7       B   West           5    200     1000           7.0
8       C  North          15    150     2250           3.5

## Merging DataFrames

In [11]:
# Creating new DataFrame for Products

product_data = {
    'Product': ['A', 'B', 'C'],
    'Category': ['Electronics', 'Furniture', 'Appliances']
}
df_products = pd.DataFrame(product_data)
df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

In [14]:
# Merge df_sales with df_products on the Product column, resulting in a new DataFrame named df_merged
# # The purpose of this merge is to add the Category column from df_products to df_sales
# Both DataFrames share the Product column which is used as the key to match rows
df_merged = pd.merge(df_sales, df_products, on="Product", how="inner")
df_merged
# Using inner merge since all products (A, B, C) exist in both DataFrames
# There are no unmatched rows so all merge types produce the same result here
# Inner is the standard choice when all keys match between both DataFrames
# Outer merge would only be needed if there were unmatched rows to preserve

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000           7.0  Electronics
1       B  South          15    200     3000           1.5    Furniture
2       C   East          20    150     3000           1.5   Appliances
3       A   West           5    100      500           9.0  Electronics
4       B  North          10    200     2000           5.0    Furniture
5       C  South          15    150     2250           3.5   Appliances
6       A   East          10    100     1000           7.0  Electronics
7       B   West           5    200     1000           7.0    Furniture
8       C  North          15    150     2250           3.5   Appliances

In [15]:
# Using groupby on df_merged to calculate the total revenue by category
# I'm grouping by category, and calculating the sum revenue on each category
df_merged.groupby('Category')[['Revenue']].sum()

             Revenue
Category
Appliances      7500
Electronics     2500
Furniture       6000